apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-load-demonstrator
  labels:
    app: system-load-demonstrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system-load-demonstrator
  template:
    metadata:
      labels:
        app: system-load-demonstrator
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
        - name: system-load-shifter-container
          image: ghcr.io/vyvahart/system-load-demonstrator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: prometheus_multiproc_dir
              value: /tmp/prometheus_multiproc_dir
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"