apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: load-shifter-monitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: system-load-demonstrator
  namespaceSelector:
    matchNames:
      - default
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 30s
    relabelings:
      - sourceLabels: [__meta_kubernetes_service_label_app]
        targetLabel: app